INSERT INTO TBL_PROFESSOR (NAME, EMAIL, PASSWORD, EDUCATION, CONDITION) VALUES ('Rodrigo', 'rodrigo@gmail.com', 'senha', 'Portugues', true);

INSERT INTO TBL_TIME (TIME) VALUES ('13:20 - 14:10');

INSERT INTO TBL_TIME (TIME) VALUES ('14:10 - 15:00');

INSERT INTO TBL_COURSE (NAME, WORKLOAD, DURATION) VALUES ('ADS', 200, 6);


